###
GET  http://localhost:3000/api/v2/users/ HTTP/1.1
Content-Type: application/json
  
{}

###
GET http://localhost:3000/api/v2/users/656d923d058091a44e6cb746 HTTP/1.1
Content-Type: application/json
  
{}

###
POST http://localhost:3000/api/v2/users/ HTTP/1.1
Content-Type: application/json
  
{
    "name": "Javiera",
    "password": "123javi",
    "email": "javi@javiera.cl",
    "role": "Alumno"
}

###
PUT http://localhost:3000/api/v2/users/656d923d058091a44e6cb746 HTTP/1.1

{
    "email": "mateo@mateo.cl",
}